### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Slattt** [realytcracker/go-jamcracker#1]
I have Golang and my paths setup correctly I believe and when I run “Go install github.com/realytcracker/go-jamcracker” it doesn’t work I get “Can’t load package : package  github.com/realytcracker/go-jamcracker cannot find package. What am I doing wrong I want this to work please.

**Comment by realytcracker** [comment]
use `go get` instead of `go install` if you didn't already clone the repo.

**Comment by Slattt** [comment]
I also tried go get a little while ago and it gave me the error “Invalid import path  : malformed import path. Do you know how I can fix this? im still new to Go.

**Comment by Slattt** [comment]
![3FDD601F-9F0B-48F4-97F7-92A3DE6AEAB1](https://user-images.githubusercontent.com/50596204/57720532-054e7580-7650-11e9-92ce-d71ed3f9d36b.jpeg)
im also getting this issue when attempting to crack.

**Comment by realytcracker** [comment]
looks like they killed the endpoint from people using it.

**Comment by Slattt** [comment]
Is there a possibility of changing the endpoint at all, to continue to use it?

**Comment by realytcracker** [comment]
i actually just checked and it is the same.  i don't know if windows has some issue with concurrency (https://stackoverflow.com/questions/28046100/golang-http-concurrent-requests-post-eof or https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi/23963271#23963271) - try running on one thread with the `-t 1` option.

**Comment by Slattt** [comment]
sorry for all the questions but how would I run on one threat i tried just putting -t 1

**Comment by realytcracker** [comment]
try running the application on a free tier amazon linux/ubuntu ec2 instance or just try it in a local virtual machine.

i don't have a windows box with golang installed to test it on (i only play elite computer games with mine) and i am pretty sure i know what to do to fix it - i might update it when i am bored, or someone can submit a pull request with the patch.  i'll update the readme to reflect the issue.

remember, this application is for education purposes only and should not be used to recover passwords of accounts that you do not own.  AJ can and will terminate your account if you're grinding their memberbase out, jacking everyone's hella rare spikes, glitch rings, and head dresses.
